# Generated by Django 4.1.7 on 2023-03-12 11:01

import django.core.files.storage
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/api/media/uploads'), unique=True, upload_to='', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.txt'], allowed_types=['text/plain'])], verbose_name='File Content'),
        ),
    ]
